server:
  port: 8081

spring:
    application:
      name: user-service
    datasource:
        url: jdbc:postgresql://user-db:5432/user_db
        username: postgres
        password: 123456
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true